apiVersion: apps/v1
kind: Deployment
metadata:
  name: custcon
  labels:
    app: custcon
spec:
  selector:
    matchLabels:
      app: custcon
  template:
    metadata:
      labels:
        app: custcon
    spec:
      containers:
      - name: proxycontainer
        image: bitnami/kubectl
        command: ["kubectl","proxy","--port=8001"]
      - name: app
        image: <image_name>
        env:
          - name: res_namespace
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace